# Generated by Django 3.2.16 on 2023-10-03 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_auto_20230924_1631"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "verbose_name": "местоположение",
                "verbose_name_plural": "Местоположения",
            },
        ),
    ]
